apiVersion: v2
name: ecommerce-category-service
description: A Helm chart for ecommerce-category-service
type: application
version: 0.0.23
appVersion: "0.0.14"

dependencies:
  - name: shared-helpers
    version: 0.5.0
    repository: "file://../shared-helpers"
