apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "template.name" . }}{{ .Values.global.configSuffix }}
data:
  APP_ENV: {{ .Values.global.config.env }}
  MONGO_HOST: {{ .Values.global.config.mongo.host }}
  KAKFA_BROKERS: {{ .Values.global.config.kafka.brokers }}
