# Local development values for ecommerce-ui
image:
  repository: sokol111/ecommerce-ui
  tag: "latest"

ingress:
  enabled: true
  host: shop.127.0.0.1.nip.io

env:
  - name: CATEGORY_QUERY_API_URL
    value: "http://ecommerce-category-query-service.dev.svc.cluster.local:8080"
  - name: PRODUCT_QUERY_API_URL
    value: "http://ecommerce-product-query-service.dev.svc.cluster.local:8080"
  - name: IMAGE_API_URL
    value: "http://ecommerce-image-service.dev.svc.cluster.local:8080"
