apiVersion: v2
name: ecommerce-product-service
description: A Helm chart for ecommerce-product-service
type: application
version: 0.0.19
appVersion: "0.0.14"

dependencies:
  - name: shared-helpers
    version: 0.1.0
    repository: "file://../shared-helpers"