apiVersion: v2
name: ecommerce-auth-service
description: A Helm chart for ecommerce-auth-service
type: application
version: 0.0.1
appVersion: "0.0.1"

dependencies:
  - name: shared-helpers
    version: 0.6.0
    repository: "file://../shared-helpers"
