name: ecommerce

services:
  redpanda:
    image: redpandadata/redpanda:v24.3.1
    container_name: redpanda
    command:
      - redpanda
      - start
      - --mode=dev-container
      - --smp=1
      - --memory=512M
      - --reserve-memory=0M
      - --overprovisioned
      - --node-id=0
      - --kafka-addr=PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:29092,PLAINTEXT_HOST://localhost:9092
      - --schema-registry-addr=0.0.0.0:8081
    ports:
      - 9092:9092   # Kafka API
      - 8084:8081   # Schema Registry
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/subjects"]
      interval: 10s
      timeout: 5s
      retries: 5

  redpanda-console:
    image: redpandadata/console:v2.8.0
    container_name: redpanda-console
    ports:
      - 9093:8080
    environment:
      KAFKA_BROKERS: redpanda:29092
      SCHEMA_REGISTRY_ENABLED: "true"
      SCHEMA_REGISTRY_URLS: http://redpanda:8081
    depends_on:
      - redpanda
    networks:
      - shared-network

networks:
  shared-network:
    external: true