name: Release GO service

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string
    secrets:
      DOCKER_PASSWORD:
        required: true

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Prepare metadata
        id: meta
        run: |
          VERSION_INPUT="${{ inputs.version }}"
          if [ -z "$VERSION_INPUT" ]; then
            VERSION_INPUT=$(cat VERSION | tr -d '\n' | tr -d '\r')
            VERSION_INPUT="v$VERSION_INPUT"
          fi
          IMAGE_NAME=sokol111/$(basename ${GITHUB_REPOSITORY})
          IMAGE_TAG="${VERSION_INPUT#v}"

          echo "version=$VERSION_INPUT" >> $GITHUB_OUTPUT
          echo "image_name=$IMAGE_NAME" >> $GITHUB_OUTPUT
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Check if tag already exists
        run: |
          if git rev-parse "refs/tags/${{ steps.meta.outputs.version }}" >/dev/null 2>&1; then
            echo "‚ùå Tag ${{ steps.meta.outputs.version }} already exists"
            exit 1
          fi

      - name: Checkout infrastructure
        uses: actions/checkout@v6
        with:
          repository: Sokol111/ecommerce-infrastructure
          path: infra

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: sokol111
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image (local)
        run: |
          IMAGE="${{ steps.meta.outputs.image_name }}"
          TAG="${{ steps.meta.outputs.image_tag }}"
          
          docker buildx build \
            -f infra/docker/Dockerfile.go \
            -t "$IMAGE:$TAG" \
            -t "$IMAGE:latest" \
            --load .

      - name: Scan image for vulnerabilities
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: '${{ steps.meta.outputs.image_name }}:${{ steps.meta.outputs.image_tag }}'
          format: 'table'
          exit-code: '1'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true

      - name: Push Docker image
        run: |
          IMAGE="${{ steps.meta.outputs.image_name }}"
          TAG="${{ steps.meta.outputs.image_tag }}"
          
          docker push "$IMAGE:$TAG"
          docker push "$IMAGE:latest"

      - name: Create Git tag
        run: |
          git tag ${{ steps.meta.outputs.version }}
          git push origin ${{ steps.meta.outputs.version }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.meta.outputs.version }}
          name: Release ${{ steps.meta.outputs.version }}
